
spring.application.name=game-access-web


spring.datasource.url=jdbc:mysql://localhost:3306/gameaccessdb?useTimezone=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=senha123456Forte
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
